name: Gatsby Publish

on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
          with:
            node-version: '14.15.4'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:all
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
